### ISSUE TITLE
Could you kindly supply the train/test image list and label in the code?

### ISSUE THREAD

**Issue by jingang-cv** [YCJGG/GDH#1]
Hi, thanks for sharing the code. Could you kindly supply the following files for reproducing the results?
'img_base.txt'
 'train_img.txt'
 'test_img.txt'
 'train_label.txt'
'train_label.txt'
 'test_label.txt'
Thank you!

**Comment by YCJGG** [comment]
Sorry for the incomplete code. 
I can not find the source files for some reasons. You can follow the settings in paper to generate these files.
"50 and 10 sketches are selected as the query sets for TU-Berlin and Sketchy respectively. The remaining   sketches and images form the training gallery. "

**Comment by LeviChenhh** [comment]
hello, asiandragon. Could you tell me how do you Create these files, in other words, could you show me one line in your file. Thank you.
